export enum ProjectLevel {
  easy = 'easy',
  medium = 'medium',
  hard = 'hard',
}

export type ProjectInfo = {
  title: string;
  description: string;
  href: string;
  level: ProjectLevel;
}

export enum ProjectLabel {
  Counter = 'Counter',
  ColorGenerator = 'ColorGenerator',
  Timer = 'Timer',
  DarkTheme = 'DarkTheme',
  CharacterCounter = 'CharacterCounter',
  FlashCards = 'FlashCards',
  CompanyStatistics = 'CompanyStatistics',
  NumberFacts = 'NumberFacts',
  TextExpander = 'TextExpander',
  StopWatch = 'StopWatch',
  Countdown = 'Countdown',
  UserSearch = 'UserSearch',
  KeyEventListener = 'KeyEventListener',
  AlarmClock = 'AlarmClock',
  RandomUserGenerator = 'RandomUserGenerator',
  APISearchTool = 'APISearchTool',
  DateCounter = 'DateCounter',
  DynamicTabs = 'DynamicTabs',
  AccordionComponent = 'AccordionComponent',
  UnitConversionTool = 'UnitConversionTool',
  AccountVerification = 'AccountVerification',
  DropdownUI = 'DropdownUI',
  TheFacts = 'TheFacts',
  CookieConsent = 'CookieConsent',
  ModalWindow = 'ModalWindow',
  GuessTheNumber = 'GuessTheNumber',
  GuessTheNumberCLI = 'GuessTheNumberCLI',
  Weather = 'Weather',
  WeatherWithRedux = 'Weather (Redux)',
  URLShortener = 'URLShortener',
  URLShortenerWithRedux = 'URLShortener (Redux)',
  ExpenseTracker = 'ExpenseTracker',
  CurrencyConverter = 'CurrencyConverter',
  SaveTextAsFile = 'SaveTextAsFile',
  // TagInputBox = 'TagInputBox',
  // WikiSearcher = 'WikiSearcher',
  // OnlineTranslator = 'OnlineTranslator',
  // ColorGenerator = 'ColorGenerator',
  // LoanCalculator = 'LoanCalculator',
  // ColorFinder = 'ColorFinder',
  // PasswordGenerator = 'PasswordGenerator',
  // TTS = 'TTS',
  // ToastNotification = 'ToastNotification',
  // RockPaperScissors = 'RockPaperScissors',
  // QRCodeScanner = 'QRCodeScanner',
  // QRCodeGenerator = 'QRCodeGenerator',
  // ProductFilter = 'ProductFilter',
  // ProductsTab = 'ProductsTab',
  // QuoteGenerator = 'QuoteGenerator',
  // Calculator = 'Calculator',
  // BreathingRelaxation = 'BreathingRelaxation',
  // HangmanGame = 'HangmanGame',
  // FeedbackForm = 'FeedbackForm',
  // Quiz = 'Quiz',
  // PasswordStrengthChecker = 'PasswordStrengthChecker',
  // RollDice = 'RollDice',
  // WorkoutTracker = 'WorkoutTracker',
  // WordScramble = 'WordScramble',
  // GitHubUsersList = 'GitHubUsersList',

  // KeyEventListener = 'KeyEventListener',
  // MemoryMatchingGame = 'MemoryMatchingGame',
  // Pokedex = 'Pokedex',
  // PriceRangeSlider = 'PriceRangeSlider',
  // TypewriterEffect = 'TypewriterEffect',
  // TypingSpeedTest = 'TypingSpeedTest',
  // ImageEditor = 'ImageEditor',
  // ImageResizer = 'ImageResizer',
  // IPAddressTracker = 'IPAddressTracker',
  // ZipCode = 'ZipCode',
  // YouTubeToMP3 = 'YouTubeToMP3',
  // CryptoMarketTracker = 'CryptoMarketTracker',
  // BreweryFinder = 'BreweryFinder',
  // CountriesExplorer = 'CountriesExplorer',
  // GitHubUserFinder = 'GitHubUserFinder',
  // JobsFilter = 'JobsFilter',
  // HackerNewsSearch = 'HackerNewsSearch',
  // MobileStoreCart = 'MobileStoreCart',
  // TheMealExplorer = 'TheMealExplorer',
  // CocktailExplorer = 'CocktailExplorer',
  // TwittyMicroposts = 'TwittyMicroposts',
  // TodoList = 'TodoList',
  // DataTableSort = 'DataTableSort',
  // UserTableSort = 'UserTableSort',
  // BookHub = 'BookHub',
  // ShoppingMarketCart = 'ShoppingMarketCart',
  // EatAndSplit = 'EatAndSplit',
  // FarAway = 'FarAway',
  // PopcornMovies = 'PopcornMovies',


}

export type ListOfProjects = Record<ProjectLabel, ProjectInfo>;